# The URL the site will be built for
base_url = "https://eversole.dev"
description = "The personal site of whom Kenneth has designed and built impactful systems that power global-scale operations, improve security, and drive efficiency. From leading infrastructure transformations at Cloudflare to optimizing AI-driven platforms at Balto, his career reflects a deep understanding of how technology shapes industries. He thrives at the intersection of engineering, business, and innovation, advising startups, conducting technical due diligence for venture capital firms, and even exploring creative storytelling through film production. Kenneth believes engineering should not only solve problems but also inspire new possibilities—pushing the boundaries of what’s possible while ensuring systems remain practical, resilient, and human-centered"
title = "Eversole.dev"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
# The default language; used in feeds.
default_language = "en"

generate_feeds = true
build_search_index = false
minify_html = true
feed_filenames = ["atom.xml"]

# The site theme to use.
taxonomies = [{ name = "tags" }]


[markdown]
highlight_code = true


[extra]

theme = "dark"

menu = [
    { name = "blog", url = "/blog", weight = 1 },
    { name = "about", url = "/about", weight = 2 },
    { name = "books", url = "/books", weight = 3 },
]

socials = [
    { name = "bluesky", url = "https://bsky.app/profile/kennetheversole.bsky.social", icon = "bluesky" },
    { name = "github", url = "https://github.com/kennetheversole/", icon = "github" },
    { name = "rss", url = "https://eversole.dev/atom.xml", icon = "rss"}
]



profile_photo = "/images/profile_photo.svg"
#profiles
github = "kennetheversole"
linkedin = "kennetheversole"
email = "kenneth@eversole.dev"

favicon = "/images/favicon.svg"
author = "Kenneth Eversole"
