# The URL the site will be built for
base_url = "https://eversole.dev"
description = "The personal site for Kenneth Eversole"
title = "Eversole.dev"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
# The default language; used in feeds.
default_language = "en"

generate_feeds = true
build_search_index = false
minify_html = true
feed_filenames = ["atom.xml"]

# The site theme to use.
taxonomies = [{ name = "tags" }]


[markdown]
highlight_code = true


[extra]

theme = "dark"

menu = [
    { name = "blog", url = "/blog", weight = 1 },
    { name = "about", url = "/about", weight = 2 },
    { name = "tags", url = "/tags", weight = 3 },
]

socials = [
    { name = "bluesky", url = "https://bsky.app/profile/kennetheversole.bsky.social", icon = "bluesky" },
    { name = "github", url = "https://github.com/kennetheversole/", icon = "github" },
    { name = "rss", url = "https://eversole.dev/atom.xml", icon = "rss"}
]



profile_photo = "/images/profile_photo.svg"
#profiles
github = "kennetheversole"
linkedin = "kennetheversole"
email = "kenneth@eversole.dev"

favicon = "/images/favicon.svg"
author = "Kenneth Eversole"
