---
name: Docker Image CI

on:
  push:
    branches:
      - master



jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Push the Image
        run: |
          docker login --username kennetheversole --password ${{ secrets.PACKAGE_SECRET }} ghcr.io
          docker build . --tag ghcr.io/kennetheversole/eversole_dev:latest
          docker push ghcr.io/kennetheversole/eversole_dev:latest
